export const BASE_BACKEND_URL = "http://localhost:8080";
export const GOOGLE_AUTH_URL = "http://localhost:8080/oauth2/authorization/google";
export const SIGN_UP_BACKEND_ENDPOINT = '/signup';
export const LOG_IN_BACKEND_ENDPOINT = '/login';
export const SIGN_UP_VERIFICATION_ENDPOINT = '/verify';
export const SIGN_UP_ROUTE = '/signup';
export const SIGN_IN_ROUTE = '/login';
export const HOME_ROUTE = '/feed';
export const CREATE_POST_ENDPOINT = '/posts';
export const SAVE_POST_ENDPOINT = CREATE_POST_ENDPOINT + '/toggle/save/';
export const REPORT_POST_ENDPOINT = CREATE_POST_ENDPOINT + '/report/';
export const DELETE_POST_ENDPOINT = CREATE_POST_ENDPOINT + '/delete';
export const FEED_ENDPOINT = CREATE_POST_ENDPOINT + '/feed';
export const EXPLORE_ENDPOINT = CREATE_POST_ENDPOINT + '/explore';
export const DIARY_ENDPOINT = CREATE_POST_ENDPOINT + '/diary';
export const SAVED_ENDPOINT = CREATE_POST_ENDPOINT + '/saved';
export const UPDATE_USER_ENDPOINT = '/user/update'
