name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Change to backend directory
        run: cd back_end
      - name: Build with Maven
        run: mvn -f back_end/pom.xml --batch-mode --update-snapshots package
      - name: Run test cases and generate coverage
        run: mvn -f back_end/pom.xml verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
